apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: remnux
spec:
  selector:
      matchLabels:
        name: remnux
  template:
    metadata:
      labels:
        name: remnux
    spec:
      nodeSelector:
        type: prod
      containers:
      - name: remnux
        image: remnux/metasploit
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi