apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: star-kernelcon2020-org
  namespace: default
spec:
  secretName: star-kernelcon2020-org-tls
  issuerRef:
    name: vault-issuer
  commonName: '*.kernelcon2020.org'
  dnsNames:
  - '*.kernelcon2020.org'