version: '3.6'

services:

  vault:
    image: vault:latest
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${vault_root_token}
      - VAULT_DEV_LISTEN_ADDRESS=127.0.0.1:8200
    cap_add:
      - IPC_LOCK
